import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: 'doc',
      id: 'Welcome',
      label: 'Welcome'
    },
    {
      type: 'category',
      label: 'Documentation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Documentation'
        }
      ]
    }
  ]
};

export default sidebars;
